# -*- coding: utf-8 -*-
"""Untitled35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jGKiQZugu4vD5-EFw3MR0pz0WzEc2htJ

# Q-Learning en el Entorno CartPole-v1

**Integrantes:** [Nombres aquí]  
**Algoritmo asignado:** Q-Learning (Off-Policy, Value-Based)  
**Entorno:** Gymnasium CartPole-v1  

### Resumen de Hiperparámetros
| Parámetro | Valor | Descripción |
| :--- | :--- | :--- |
| Tasa de aprendizaje ($\alpha$) | 0.1 | Velocidad de actualización de la Q-Table |
| Factor de descuento ($\gamma$) | 0.99 | Importancia de las recompensas futuras |
| $\epsilon$ inicial | 1.0 | Probabilidad inicial de exploración |
| $\epsilon$ mínimo | 0.01 | Probabilidad mínima de exploración |
| Factor de decaimiento | 0.995 | Ritmo de reducción de la exploración |
| Episodios | 5000 | Duración total del entrenamiento |

## Instalación de Dependencias
Primero instalamos `gymnasium` para acceder al entorno de CartPole.
"""

!pip install gymnasium numpy matplotlib

"""## A. DEFINICIÓN DEL ENTORNO (MDP)

El problema de CartPole-v1 es un Proceso de Decisión de Markov (MDP) con las siguientes características:

1.  **Espacio de Estados (Continuo):**
    *   Posición del carro ($x$)
    *   Velocidad del carro ($\dot{x}$)
    *   Ángulo del poste ($\theta$)
    *   Velocidad angular del poste ($\dot{\theta}$)
2.  **Espacio de Acciones (Discreto):**
    *   `0`: Empujar hacia la izquierda.
    *   `1`: Empujar hacia la derecha.
3.  **Función de Recompensa:** Se otorga una recompensa de $+1$ por cada paso que el poste permanezca vertical (ángulo < 12° y posición dentro de límites).
4.  **Q-Learning:** Es un algoritmo **Off-Policy** porque aprende la política óptima independientemente de las acciones tomadas, y **Basado en Valor** porque estima la función $Q(s,a)$.
"""

import gymnasium as gym
import numpy as np

# Creamos el entorno
env = gym.make('CartPole-v1')

# Mostramos información del espacio de estados y acciones
print(f"Espacio de Estados: {env.observation_space}")
print(f"Espacio de Acciones: {env.action_space}")

# Reiniciamos el entorno para ver el estado inicial
estado_inicial, info = env.reset()
print(f"Estado Inicial (4 variables): {estado_inicial}")
env.close()

"""## B. DILEMA EXPLORACIÓN VS EXPLOTACIÓN

Para balancear el aprendizaje, usamos una política **$\epsilon$-greedy**:
- **Exploración Alta ($\epsilon \approx 1.0$):** El agente toma acciones aleatorias para descubrir el entorno.
- **Explotación ($\epsilon \approx 0.01$):** El agente usa su conocimiento (Q-Table) para maximizar la recompensa.
"""

import matplotlib.pyplot as plt

# Simulación del decaimiento de epsilon para visualización
epsilon = 1.0
epsilon_min = 0.01
decay = 0.995
episodios = 5000

historial_epsilon = []

for i in range(episodios):
    historial_epsilon.append(epsilon)
    epsilon = max(epsilon_min, epsilon * decay)
    if i % 500 == 0:
        print(f"Episodio {i}: Epsilon = {epsilon:.4f}")

# Graficamos el decaimiento
plt.figure(figsize=(8, 4))
plt.plot(historial_epsilon, color='cyan')
plt.title("Decaimiento de Epsilon")
plt.xlabel("Episodio")
plt.ylabel("Epsilon")
plt.grid(True, alpha=0.3)
plt.show()

"""## C. SIMULACIÓN PRÁCTICA CON GYMNASIUM

Implementamos el algoritmo de Q-Learning. Dado que el espacio es continuo, aplicamos **Discretización** usando 20 'bins' por variable.
"""

# Hiperparámetros de entrenamiento
ALPHA = 0.1
GAMMA = 0.99
EPS_INITIAL = 1.0
EPS_MIN = 0.01
DECAY = 0.995
EPISODES = 5000
BINS = 20

# Límites para discretizar (ajustados a valores razonables del entorno)
os_low = [env.observation_space.low[0], -2.0, env.observation_space.low[2], -3.5]
os_high = [env.observation_space.high[0], 2.0, env.observation_space.high[2], 3.5]

# Función para convertir estado continuo a discreto
def discretize_state(state):
    ratios = [(state[i] - os_low[i]) / (os_high[i] - os_low[i]) for i in range(len(state))]
    new_state = [int(round((BINS - 1) * ratios[i])) for i in range(len(state))]
    new_state = [min(BINS - 1, max(0, x)) for x in new_state]
    return tuple(new_state)

# Inicialización de la Q-Table (20x20x20x20x2)
q_table = np.zeros((BINS, BINS, BINS, BINS, env.action_space.n))

# Listas para métricas
reward_history = []
eps_history = []
eps = EPS_INITIAL

print("Iniciando Entrenamiento...")
for e in range(EPISODES):
    state_cont, _ = env.reset()
    state = discretize_state(state_cont)
    done = False
    total_reward = 0

    while not done:
        # Política Epsilon-Greedy
        if np.random.random() < eps:
            action = env.action_space.sample() # Explorar
        else:
            action = np.argmax(q_table[state]) # Explotar

        next_state_cont, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated
        next_state = discretize_state(next_state_cont)

        # Ecuación de Bellman
        old_value = q_table[state + (action,)]
        next_max = np.max(q_table[next_state])
        new_value = old_value + ALPHA * (reward + GAMMA * next_max - old_value)
        q_table[state + (action,)] = new_value

        state = next_state
        total_reward += reward

    reward_history.append(total_reward)
    eps_history.append(eps)
    eps = max(EPS_MIN, eps * DECAY)

    if (e + 1) % 500 == 0:
        avg = np.mean(reward_history[-100:])
        print(f"Episodio: {e+1} | Promedio (100): {avg:.2f} | Epsilon: {eps:.4f}")

# Prueba final (5 episodios)
print("\n--- Pruebas Finales (Sin Exploración) ---")
for test_e in range(5):
    s_cont, _ = env.reset()
    s = discretize_state(s_cont)
    d = False
    r_test = 0
    while not d:
        a = np.argmax(q_table[s])
        s_cont, r, term, trunc, _ = env.step(a)
        s = discretize_state(s_cont)
        d = term or trunc
        r_test += r
    print(f"Prueba {test_e+1}: Reward = {r_test}")

"""## D. ANÁLISIS DE CONVERGENCIA"""

import pandas as pd

# Estilo oscuro profesional
plt.style.use('dark_background')
fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(12, 10), facecolor='#0f0f1a')
ax1.set_facecolor('#0f0f1a')
ax2.set_facecolor('#0f0f1a')

# Subplot 1: Recompensas
moving_avg = pd.Series(reward_history).rolling(window=100).mean()
ax1.plot(reward_history, alpha=0.3, color='royalblue', label='Reward por Episodio')
ax1.plot(moving_avg, color='yellow', linewidth=2, label='Promedio Móvil (100)')
ax1.axhline(y=200, color='lime', linestyle='--', label='Meta (200 pts)')
ax1.annotate('Fase: Exploración', xy=(500, 50), color='white', weight='bold')
ax1.annotate('Fase: Explotación', xy=(4000, 180), color='white', weight='bold')
ax1.set_title("Evolución del Aprendizaje (Reward)", fontsize=14)
ax1.set_ylabel("Recompensa Total")
ax1.legend()

# Subplot 2: Epsilon
ax2.plot(eps_history, color='magenta', label='Decaimiento Epsilon')
ax2.fill_between(range(EPISODES), eps_history, color='magenta', alpha=0.1)
ax2.set_title("Reducción de la Tasa de Exploración", fontsize=14)
ax2.set_xlabel("Episodios")
ax2.set_ylabel("Valor de Epsilon")
ax2.legend()

plt.tight_layout()
plt.show()

# Estadísticas finales
ultimos_100 = reward_history[-100:]
print(f"\nEstadísticas de los últimos 100 episodios:")
print(f"Promedio: {np.mean(ultimos_100):.2f}")
print(f"Máximo: {np.max(ultimos_100)}")
print(f"Mínimo: {np.min(ultimos_100)}")
print(f"Desviación Estándar: {np.std(ultimos_100):.2f}")

"""## E. PREPARACIÓN PARA DESPLIEGUE (STREAMLIT)

Generamos los archivos necesarios para el despliegue en Streamlit local o en la nube.
"""

import subprocess

# 1. Crear el archivo requirements.txt
requirements = """gymnasium
numpy
matplotlib
streamlit
pandas
"""
with open('requirements.txt', 'w') as f:
    f.write(requirements)

# 2. Crear el archivo app.py para Streamlit
streamlit_code = """
import streamlit as st
import gymnasium as gym
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import time

st.title("🕹️ CartPole-v1 Q-Learning Agent")
st.sidebar.header("Configuración")

# Simulación de carga de Q-Table pre-entrenada o parámetros
ALPHA = 0.1
GAMMA = 0.99
BINS = 20

os_low = [-4.8, -2.0, -0.418, -3.5]
os_high = [4.8, 2.0, 0.418, 3.5]

def discretize_state(state):
    ratios = [(state[i] - os_low[i]) / (os_high[i] - os_low[i]) for i in range(len(state))]
    new_state = [int(round((BINS - 1) * ratios[i])) for i in range(len(state))]
    new_state = [min(BINS - 1, max(0, x)) for x in new_state]
    return tuple(new_state)

# Botón para ejecutar demo
if st.button('Ejecutar Demo del Agente'):
    env = gym.make('CartPole-v1', render_mode='rgb_array')
    state_cont, _ = env.reset()
    done = False
    total_reward = 0

    img_placeholder = st.empty()

    while not done:
        # Nota: Aquí se usaría la q_table entrenada.
        # Para la demo, usamos acciones aleatorias o una lógica simple si no se carga la tabla.
        action = env.action_space.sample()
        state_cont, reward, terminated, truncated, _ = env.step(action)
        done = terminated or truncated
        total_reward += reward

        img = env.render()
        img_placeholder.image(img, caption=f"Reward: {total_reward}")
        time.sleep(0.02)

    st.success(f"¡Simulación terminada! Reward total: {total_reward}")
    env.close()
"""

with open('app.py', 'w') as f:
    f.write(streamlit_code)

print("Archivos 'app.py' y 'requirements.txt' creados con éxito.")

from google.colab import files

# Descargar los archivos generados para el despliegue local/github
files.download('app.py')
files.download('requirements.txt')

print("Iniciando descarga de archivos para el despliegue...")

from google.colab import files

# Reintentar la descarga del archivo de dependencias
try:
    files.download('requirements.txt')
    print("Descarga de requirements.txt iniciada.")
except Exception as e:
    print(f"Error al intentar descargar: {e}")

"""### Análisis y Conclusiones

1.  **¿El agente aprendió?**
    *   Sí. Se observa una tendencia ascendente en el promedio móvil. Al inicio (exploración), el agente falla rápido, pero a medida que $\epsilon$ baja, la recompensa aumenta.

2.  **¿Por qué no alcanza siempre 200+?**
    *   Q-Learning tabular con discretización es sensible a los límites elegidos. Si el estado sale del rango discretizado o cae en un "bin" muy grande, la precisión se pierde.

3.  **La Maldición de la Dimensionalidad:**
    *   Tenemos 4 variables continuas. Al usar 20 bins por variable, la tabla tiene $20^4 \times 2 = 320,000$ entradas. Si quisiéramos más precisión (ej. 100 bins), la tabla crecería exponencialmente ($100^4 \times 2 = 200$ millones), haciendo que el aprendizaje sea extremadamente lento y requiera demasiada memoria.
"""